config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :categories, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]

  # get '/categories', to: 'categories#index'
  # get '/categories/:id', to: 'categories#show'
  # get '/categories/new', to: 'categories#new'
  # post '/categories', to: 'categories#create'
  # get '/categories/:id/bookmarks/new', to: 'bookmarks#new'
  # post '/categories/id/bookmarks', to: 'bookmarks#create'
  # delete '/bookmarks/:id', to: 'bookmarks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
  validates :recipe_id, uniqueness: { scope: :category_id, message: 'has already been added to this category' }
  validates :comment, length: { minimum: 6 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<div class="form-center mt-5">
  <h2>Add a Receipe to <%= @category.name %></h2>

  <%= simple_form_for [@category, @bookmark] do |f| %>
    <%= f.association :recipe %>
    <%= f.input :comment %>
    <%= f.submit class: "btn btn-warning"%>
  <% end %>

  <div class="pt-3">
    <%= link_to "Back to #{@category.name} recipes", category_path(@category) %>
  <div>
</div>

app/views/categories/index.html.erb
<%= render "shared/banner" %>

<div class="container w-75 mb-5">
  <div class="info-top">
    <h2>List of Categories</h2>
    <%= link_to "New category", new_category_path, class:"btn btn-warning" %>
  </div>

  <div class="cards">
    <% @categories.each do |category| %>
      <%= link_to category_path(category) do %>
      <% if category.photo.attached? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path category.photo.key %>')">
      <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(19, 12, 12, 0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <% end %>
          <div>
            <h3><%= category.name %></h3>
            <p><%= category.bookmarks.count %> recipes</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="form-center mt-5">
  <h2>Add a new Category</h2>

  <%= simple_form_for(@category) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Create Category", class: "btn btn-warning"%>
  <% end %>
<div>

app/views/categories/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path @category.photo.key %>')">
  <div>
    <h1><%= @category.name.upcase %></h1>
  </div>
</div>

<div class="container w-75 mb-5">
  <div class="info-top">
    <h2><%= @category.name %> recipes</h2>
    <%= link_to "Add a recipe", new_category_bookmark_path(@category), class:"btn btn-warning" %>
  </div>

  <div class="cards">
    <% @category.bookmarks.each do |bookmark| %>
      <div class="card-trip">
        <img src="<%= bookmark.recipe.image_url %>" alt="<%= bookmark.recipe.name %>">
        <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn-delete" do %>
          <i class="fa-sharp-duotone fa-regular fa-trash-can"></i>
        <% end %>
        <div class="card-trip-description">
          <h2><%= bookmark.recipe.name %></h2>
          <p><%= bookmark.recipe.description.truncate(100) %></p>
        </div>

        <div class="card-trip-infos">
          <div>
            <p><strong class="quot-bold">“</strong> <%= bookmark.comment %></p>
          </div>

          <div>
            <%= bookmark.recipe.rating %> <%= '⭐' * bookmark.recipe.rating.floor %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= image_path "banner.jpg" %>')">
  <div>
    <h1>Cookbook</h1>
    <h3>Save your favorite recipes</h3>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# <nav id="navbar-example2" class="navbar bg-body-tertiary px-3 mb-3"> %>
<nav class="navbar bg-white px-3">
  <%= link_to categories_path do %>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAhrGds2qxYp3syFi7EQCUYHpn-eq3TQidHg&s" alt="cookbook logo" width="40px">
  <% end %>

  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to "Home", categories_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "New category",  new_category_path, class:"nav-link" %>
    </li>
  </ul>
</nav>